export interface Tile {
  type: number; // 0=empty, 1=platform, 2=ladder, 3=collectible, 4=enemy, 5=player, 6=exit
}

export interface Level {
  name: string;
  width: number;
  height: number;
  tiles: Tile[];
  playerStart: { x: number; y: number };
  enemies: Array<{ x: number; y: number }>;
}

const TILE_SIZE = 40;

function createLevel(name: string, width: number, height: number, data: number[]): Level {
  const tiles = data.map(t => ({ type: t }));

  let playerStart = { x: 0, y: 0 };
  const enemies: Array<{ x: number; y: number }> = [];

  for (let i = 0; i < data.length; i++) {
    if (data[i] === 5) {
      playerStart = { x: (i % width) * TILE_SIZE, y: Math.floor(i / width) * TILE_SIZE };
      tiles[i].type = PLATFORM; // Make spawn position solid
    }
    if (data[i] === 4) enemies.push({ x: (i % width) * TILE_SIZE, y: Math.floor(i / width) * TILE_SIZE });
  }

  return { name, width, height, tiles, playerStart, enemies };
}

const EMPTY = 0;
const PLATFORM = 1;
const LADDER = 2;
const COLLECTIBLE = 3;
const ENEMY = 4;
const PLAYER = 5;
const EXIT = 6;

// Level 1: Simple intro (16x12)
const level1Data = [
  6,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,
  PLATFORM,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,PLATFORM,
  EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,
  PLATFORM,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,EMPTY,EMPTY,PLATFORM,
  EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,
  PLATFORM,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,PLATFORM,
  EMPTY,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,
  PLATFORM,PLATFORM,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,PLATFORM,PLATFORM,PLATFORM,
  EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,
  PLATFORM,PLATFORM,PLATFORM,PLATFORM,LADDER,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,LADDER,PLATFORM,PLATFORM,PLATFORM,
  EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,
  PLAYER,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,
];

// Level 2: Medium difficulty (16x12)
const level2Data = [
  EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EXIT,
  PLATFORM,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,PLATFORM,
  EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,
  PLATFORM,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,PLATFORM,
  EMPTY,EMPTY,EMPTY,LADDER,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,COLLECTIBLE,EMPTY,EMPTY,EMPTY,
  PLATFORM,EMPTY,EMPTY,LADDER,PLATFORM,PLATFORM,EMPTY,EMPTY,PLATFORM,PLATFORM,EMPTY,LADDER,PLATFORM,EMPTY,EMPTY,PLATFORM,
  EMPTY,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,
  PLATFORM,PLATFORM,EMPTY,EMPTY,ENEMY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,PLATFORM,PLATFORM,PLATFORM,
  EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,
  PLATFORM,PLATFORM,PLATFORM,LADDER,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,EMPTY,LADDER,PLATFORM,PLATFORM,
  EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,ENEMY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,
  PLAYER,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,
];

// Level 3: Hard (16x12)
const level3Data = [
  EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EXIT,
  PLATFORM,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,ENEMY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,PLATFORM,
  EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,
  PLATFORM,LADDER,EMPTY,LADDER,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,COLLECTIBLE,LADDER,EMPTY,PLATFORM,
  EMPTY,EMPTY,EMPTY,LADDER,PLATFORM,PLATFORM,EMPTY,EMPTY,PLATFORM,PLATFORM,EMPTY,LADDER,PLATFORM,EMPTY,EMPTY,EMPTY,
  PLATFORM,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,PLATFORM,
  EMPTY,COLLECTIBLE,LADDER,EMPTY,ENEMY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,ENEMY,EMPTY,LADDER,COLLECTIBLE,EMPTY,
  PLATFORM,PLATFORM,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,PLATFORM,PLATFORM,
  EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LADDER,EMPTY,EMPTY,
  PLATFORM,PLATFORM,PLATFORM,LADDER,PLATFORM,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,PLATFORM,PLATFORM,EMPTY,LADDER,PLATFORM,PLATFORM,
  EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COLLECTIBLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,
  PLAYER,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,PLATFORM,
];

export const LEVELS = [
  createLevel("Level 1", 16, 12, level1Data),
  createLevel("Level 2", 16, 12, level2Data),
  createLevel("Level 3", 16, 12, level3Data),
];

export const TILE_SIZE_PX = TILE_SIZE;
